spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chatapp?currentSchema=chatapp
    username: chatapp_user
    password: dev_password_123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        default_schema: chatapp
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    com.talkweb: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
