spring:
  application:
    name: talkweb-app
  profiles:
    active: dev
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      continue-on-error: true

server:
  port: 8080
  servlet:
    context-path: /

app:
  jwt:
    secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
    expiration-ms: 86400000 # 24 hours
  avatar:
    max-size-kb: ${AVATAR_MAX_SIZE_KB:500}
